## numpy indexing and slicing of vectors

In [1]:
import numpy as np

In [2]:
arr = np.arange(1, 11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[9] # access the 10th element (index starts from 0)

np.int64(10)

In [4]:
arr[1:5] # slice the array from index 1 to 4 (5 is exclusive)

array([2, 3, 4, 5])

In [5]:
arr[:5] # slice the array from the beginning to index 4 (5 is exclusive)

array([1, 2, 3, 4, 5])

In [6]:
arr[3:] # slice the array from index 3 to the end

array([ 4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[3::2] # slice the array from index 3 to the end, with a step of 2 (every other element)

array([ 4,  6,  8, 10])

## numpy indexing and slicing of matrix

In [9]:
arr = np.arange(1, 31).reshape(5, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [11]:
arr[0] # first row

array([1, 2, 3, 4, 5, 6])

In [12]:
arr[3] # fourth row (index starts from 0)

array([19, 20, 21, 22, 23, 24])

In [13]:
arr[0,0] # first element of the first row

np.int64(1)

In [16]:
arr[0,5] # last element of the first row

np.int64(6)

In [18]:
arr[4,5] # last  element of the last row


np.int64(30)

In [22]:
# arr[start_row:end_row, start_col:end_col]
arr[0:2, 0:3] # slice the first two rows and the first three columns

array([[1, 2, 3],
       [7, 8, 9]])

In [20]:
arr[0:2, 1:3] # slice the first two rows and the second and third columns

array([[2, 3],
       [8, 9]])

In [23]:
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [28]:
arr[3:5, 3:6] # slice the last two rows and the last three columns

array([[22, 23, 24],
       [28, 29, 30]])

In [29]:
arr[:5] # slice the array from the beginning to index 4 (5 is exclusive)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [30]:
arr[:,2] # slice all rows and the third column (index 2)

array([ 3,  9, 15, 21, 27])

## Boolean Indexing

In [32]:
arr = np.arange(12, 21)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [33]:
bool_index = arr%2 == 0 # create a boolean index for even numbers
bool_index

array([ True, False,  True, False,  True, False,  True, False,  True])

In [34]:
arr = arr[bool_index] # use the boolean index to filter the array
arr

array([12, 14, 16, 18, 20])

## Array Operations

### Arithmetic operations

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
# element size must be the same for array operations
a1 + a2 # element-wise addition

array([ 7,  9, 11, 13, 15])

In [4]:
a1-a2 # element-wise subtraction

array([-5, -5, -5, -5, -5])

In [5]:
a1*a2 # element-wise multiplication

array([ 6, 14, 24, 36, 50])

In [6]:
a1/a2 # element-wise division

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [7]:
a1//a2 # element-wise floor division (integer division)

array([0, 0, 0, 0, 0])

In [8]:
a1**2 # element-wise exponentiation (squaring each element)

array([ 1,  4,  9, 16, 25])

In [9]:
l = [10, 20, 30, 40, 50]
arr = np.array(l) # convert list to numpy array

In [10]:
arr+10 # add 10 to each element of the array

array([20, 30, 40, 50, 60])

In [14]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr2 = arr2 + 10 # add 10 to each element of the array
arr2

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [17]:
# Deep copy vs Shallow copy
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [18]:
slice = a[0:5] # create a slice of the array (shallow copy)
slice = slice + 10 # modify the slice
slice

array([11, 12, 13, 14, 15])

In [19]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
a1 = a[4:6]**2 # modify the shallow copy (slice) and assign it to a new variable (a1)
a1 


array([25, 36])

In [22]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

## Matrix Operations

In [24]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [25]:
A

array([[1, 2],
       [3, 4]])

In [26]:
B

array([[5, 6],
       [7, 8]])

In [27]:
# multiply A and B element-wise
A * B

array([[ 5, 12],
       [21, 32]])

In [28]:
A @ B # matrix multiplication (dot product) of A and B

array([[19, 22],
       [43, 50]])

In [29]:
np.dot(A, B) # another way to perform matrix multiplication (dot product) of A and B

array([[19, 22],
       [43, 50]])

In [30]:
# transpose of A
A.T

array([[1, 3],
       [2, 4]])

In [31]:
A

array([[1, 2],
       [3, 4]])

In [32]:
B

array([[5, 6],
       [7, 8]])

In [34]:
# stck array
a = np.arange(1, 11).reshape(2, 5)
b = np.arange(11, 21).reshape(2, 5)

In [35]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [36]:
b

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [37]:
# vertical stack (stack arrays vertically)
np.vstack((a, b))

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [38]:
# horizontal stack (stack arrays horizontally)
np.hstack((a, b))

array([[ 1,  2,  3,  4,  5, 11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10, 16, 17, 18, 19, 20]])

In [43]:
# spliting arrays
arr = np.arange(16).reshape(4, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [44]:
# horizontal split the array into 2 sub-arrays
np.hsplit(arr, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
np.hsplit(arr, 3) ## show error: array split does not result in an equal division

ValueError: array split does not result in an equal division

In [ ]:
np.split(arr, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]