In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [3]:
a = [1, 2, 3, 4, 5]

In [4]:
np_arr = np.array(a)
print(np_arr)

[1 2 3 4 5]


In [ ]:
lst = [1, 2, 3, 4, 5, "hello", 3.14]
np_lst = np.array(lst) # converts list to numpy array with string data type
print(np_lst)

['1' '2' '3' '4' '5' 'hello' '3.14']


In [7]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np_arr = np.array(l)
np_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np_arr.shape

(3, 3)

In [12]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr = np.ones((2,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1, 10, 5)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## Random Generation

In [18]:
np.random.rand(3,4) # generates random numbers between 0 and 1 in a 3x4 array

array([[0.55312829, 0.29213502, 0.77690579, 0.88437578],
       [0.36499158, 0.99026648, 0.9033539 , 0.89211757],
       [0.80257891, 0.41767751, 0.53248005, 0.35527065]])

In [20]:
np.random.randn(10) # generates random numbers from a standard normal distribution in a 10-element array

array([ 1.99346565,  0.09827009, -0.03154335, -0.38127463, -0.52916783,
        1.9888201 ,  0.25587128, -0.33416865,  0.44754406,  0.526192  ])

In [28]:
np.random.randint(0, 6) # generates a single random number between 0 and 6

2

## Array Attributes

In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [31]:
arr.shape

(2, 3)

In [32]:
arr.size

6

In [33]:
arr.dtype

dtype('int64')

<!-- array method -->
## Array Method

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
arr.min()

np.int64(1)

In [36]:
arr.max()

np.int64(6)

In [37]:
arr.sum()

np.int64(21)

In [39]:
np.sum(arr, axis=0) # sum along columns

array([5, 7, 9])

In [41]:
np.sum(arr, axis = 1) # sum along rows

array([ 6, 15])

In [42]:
arr.mean() # mean of all elements in the array

np.float64(3.5)

In [43]:
arr.std() # standard deviation of all elements in the array

np.float64(1.707825127659933)

In [44]:
arr.argmax() # index of the maximum element in the array

np.int64(5)

In [45]:
arr.argmin() # index of minimum element in the array

np.int64(0)

## Reshaping and resizing

In [47]:
arr = np.arange(1, 31) # creates a 1D array with values from 1 to 30
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr.reshape(5, 6) # reshapes the array to 5 rows and 6 columns
# if the total number of elements does not match, it will raise an error
# 5*6 = 30, which matches the total number of elements in the original array (1 to 30)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])